CREATE TABLE commands (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus text NOT NULL,
    kind text NOT NULL,
    dedupe_key text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT commands_bus_not_blank CHECK (btrim(bus) <> ''),
    CONSTRAINT commands_kind_not_blank CHECK (btrim(kind) <> ''),
    CONSTRAINT commands_dedupe_key_not_blank CHECK (
        dedupe_key IS NULL OR btrim(dedupe_key) <> ''
    )
);

CREATE UNIQUE INDEX idx_commands_bus_kind_dedupe_key
    ON commands (bus, kind, dedupe_key)
    WHERE dedupe_key IS NOT NULL;

CREATE INDEX idx_commands_bus_kind_created_at
    ON commands (bus, kind, created_at DESC);

CREATE TRIGGER trg_commands_set_updated_at
BEFORE UPDATE ON commands
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

DROP TABLE IF EXISTS thread_processed_commands;

UPDATE spawn_groups
SET aggregate_cmd_id = NULL
WHERE aggregate_cmd_id IS NOT NULL;

ALTER TABLE spawn_groups
    DROP CONSTRAINT IF EXISTS spawn_groups_aggregate_cmd_id_fkey;

DROP INDEX IF EXISTS idx_spawn_groups_aggregate_cmd_id;

ALTER TABLE spawn_groups
    ALTER COLUMN aggregate_cmd_id TYPE bigint
    USING NULL::bigint;

ALTER TABLE spawn_groups
    ADD CONSTRAINT spawn_groups_aggregate_cmd_id_fkey
    FOREIGN KEY (aggregate_cmd_id) REFERENCES commands (id) ON DELETE SET NULL;

CREATE INDEX idx_spawn_groups_aggregate_cmd_id
    ON spawn_groups (aggregate_cmd_id)
    WHERE aggregate_cmd_id IS NOT NULL;

CREATE TABLE thread_processed_commands (
    thread_id bigint NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
    cmd_id bigint NOT NULL REFERENCES commands (id) ON DELETE CASCADE,
    processed_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (thread_id, cmd_id),
    CONSTRAINT thread_processed_commands_cmd_id_positive CHECK (cmd_id > 0)
);

CREATE INDEX idx_thread_processed_commands_cmd_id
    ON thread_processed_commands (cmd_id, processed_at DESC);
