-- Evidence-chain citations.
--
-- A citation is a thread-scoped pointer into a document: the root thread
-- produced it via store_citation, it references one document, and it
-- materializes one or two (N, N+1 consecutive) pages of bboxes. The model
-- embeds [display text][citation_id] markers in its response; the frontend
-- resolves the id via this table and paints the bboxes on the PDF.
--
-- citation_bboxes.line_indices is the canonical identity (indices into the
-- page's OCR lines[] array). bbox_x/y/width/height is the unioned envelope,
-- denormalized from those lines for fast paint-time access. poly_json holds
-- the OCR poly points for future rotation-aware rendering.
CREATE TABLE IF NOT EXISTS citations (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    root_thread_id    bigint NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    document_id       bigint NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    instruction       text NOT NULL DEFAULT '',
    created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_citations_root_thread_id
    ON citations (root_thread_id);

CREATE INDEX IF NOT EXISTS idx_citations_document_id
    ON citations (document_id);

CREATE TABLE IF NOT EXISTS citation_bboxes (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    citation_id   bigint NOT NULL REFERENCES citations(id) ON DELETE CASCADE,
    page          integer NOT NULL,
    line_indices  integer[] NOT NULL,
    bbox_x        integer NOT NULL,
    bbox_y        integer NOT NULL,
    bbox_width    integer NOT NULL,
    bbox_height   integer NOT NULL,
    poly_json     jsonb,
    created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_citation_bboxes_citation_id
    ON citation_bboxes (citation_id);
