DROP TABLE IF EXISTS spawn_group_children;
DROP TABLE IF EXISTS spawn_groups;

UPDATE threads
SET active_spawn_group_id = NULL
WHERE active_spawn_group_id IS NOT NULL;

ALTER TABLE threads
    ALTER COLUMN active_spawn_group_id TYPE bigint USING NULL;

CREATE TABLE spawn_groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_thread_id bigint NOT NULL REFERENCES threads (id) ON DELETE RESTRICT,
    parent_call_id text NOT NULL,
    group_kind text NOT NULL,
    stable_key text,
    expected integer NOT NULL,
    completed integer NOT NULL DEFAULT 0,
    failed integer NOT NULL DEFAULT 0,
    cancelled integer NOT NULL DEFAULT 0,
    status text NOT NULL,
    aggregate_submitted_at timestamptz,
    aggregate_cmd_id text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT spawn_groups_expected_nonnegative CHECK (expected >= 0),
    CONSTRAINT spawn_groups_completed_nonnegative CHECK (completed >= 0),
    CONSTRAINT spawn_groups_failed_nonnegative CHECK (failed >= 0),
    CONSTRAINT spawn_groups_cancelled_nonnegative CHECK (cancelled >= 0),
    CONSTRAINT spawn_groups_counts_within_expected CHECK (completed + failed + cancelled <= expected),
    CONSTRAINT spawn_groups_kind_valid CHECK (
        group_kind IN (
            'document_query',
            'thread_spawn'
        )
    ),
    CONSTRAINT spawn_groups_status_valid CHECK (
        status IN (
            'waiting',
            'closed',
            'cancelled'
        )
    )
);

CREATE INDEX idx_spawn_groups_parent_thread_id
    ON spawn_groups (parent_thread_id, created_at);

CREATE UNIQUE INDEX idx_spawn_groups_document_query_stable_key
    ON spawn_groups (parent_thread_id, group_kind, stable_key)
    WHERE stable_key IS NOT NULL;

CREATE TRIGGER trg_spawn_groups_set_updated_at
BEFORE UPDATE ON spawn_groups
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE spawn_group_children (
    spawn_group_id bigint NOT NULL REFERENCES spawn_groups (id) ON DELETE CASCADE,
    child_thread_id bigint NOT NULL REFERENCES threads (id) ON DELETE RESTRICT,
    child_index integer,
    status text NOT NULL DEFAULT 'pending',
    child_response_id text,
    assistant_text text,
    result_ref text,
    summary_ref text,
    error_ref text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (spawn_group_id, child_thread_id),
    CONSTRAINT spawn_group_children_index_nonnegative CHECK (child_index IS NULL OR child_index >= 0),
    CONSTRAINT spawn_group_children_status_valid CHECK (
        status IN (
            'pending',
            'completed',
            'failed',
            'cancelled'
        )
    )
);

CREATE INDEX idx_spawn_group_children_status
    ON spawn_group_children (spawn_group_id, status);

CREATE INDEX idx_spawn_group_children_child_thread_id
    ON spawn_group_children (child_thread_id);

CREATE TRIGGER trg_spawn_group_children_set_updated_at
BEFORE UPDATE ON spawn_group_children
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
