DROP TABLE IF EXISTS collection_documents;
DROP TABLE IF EXISTS thread_documents;
DROP TABLE IF EXISTS documents;

CREATE TABLE IF NOT EXISTS documents (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_ref          text NOT NULL,
    status              text NOT NULL DEFAULT 'pending',
    error               text NOT NULL DEFAULT '',
    manifest_ref        text NOT NULL DEFAULT '',
    page_count          integer NOT NULL DEFAULT 0,
    dpi                 integer NOT NULL DEFAULT 150,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    filename            text NOT NULL DEFAULT '',
    base_response_id    text NOT NULL DEFAULT '',
    base_model          text NOT NULL DEFAULT '',
    base_initialized_at timestamptz,
    query_model         text NOT NULL DEFAULT 'gpt-5.4'
);

CREATE INDEX IF NOT EXISTS idx_documents_status ON documents (status);
CREATE INDEX IF NOT EXISTS idx_documents_created_at ON documents (created_at DESC);

CREATE TABLE IF NOT EXISTS thread_documents (
    thread_id    text NOT NULL REFERENCES threads(id) ON DELETE CASCADE,
    document_id  bigint NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    created_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (thread_id, document_id)
);

CREATE INDEX IF NOT EXISTS idx_thread_documents_document_id
    ON thread_documents (document_id);

CREATE TABLE IF NOT EXISTS collection_documents (
    collection_id  text NOT NULL REFERENCES collections(id) ON DELETE CASCADE,
    document_id    bigint NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
    created_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, document_id)
);

CREATE INDEX IF NOT EXISTS idx_collection_documents_document_id ON collection_documents (document_id);
