DROP TABLE IF EXISTS openai_socket_sessions;
DROP TABLE IF EXISTS thread_owners;

ALTER TABLE threads
    DROP CONSTRAINT IF EXISTS threads_owner_worker_id_fkey;

DROP INDEX IF EXISTS idx_threads_owner_worker_id;

ALTER TABLE threads
    ALTER COLUMN owner_worker_id TYPE bigint
    USING NULL::bigint;

CREATE TABLE workers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name text NOT NULL,
    nats_client_name text,
    responses_ws_url text,
    lease_until timestamptz NOT NULL,
    started_at timestamptz NOT NULL DEFAULT now(),
    last_heartbeat_at timestamptz NOT NULL DEFAULT now(),
    stopped_at timestamptz,
    stop_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT workers_service_name_not_blank CHECK (btrim(service_name) <> ''),
    CONSTRAINT workers_last_heartbeat_after_start CHECK (last_heartbeat_at >= started_at),
    CONSTRAINT workers_stopped_after_start CHECK (stopped_at IS NULL OR stopped_at >= started_at)
);

CREATE INDEX idx_workers_active_lease
    ON workers (lease_until DESC)
    WHERE stopped_at IS NULL;

CREATE INDEX idx_workers_service_started
    ON workers (service_name, started_at DESC);

CREATE TRIGGER trg_workers_set_updated_at
BEFORE UPDATE ON workers
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

ALTER TABLE threads
    ADD CONSTRAINT threads_owner_worker_id_fkey
    FOREIGN KEY (owner_worker_id) REFERENCES workers (id) ON DELETE SET NULL;

CREATE INDEX idx_threads_owner_worker_id
    ON threads (owner_worker_id)
    WHERE owner_worker_id IS NOT NULL;

CREATE TABLE thread_owners (
    thread_id bigint PRIMARY KEY REFERENCES threads (id) ON DELETE CASCADE,
    worker_id bigint NOT NULL REFERENCES workers (id),
    lease_until timestamptz NOT NULL,
    socket_generation bigint NOT NULL,
    claimed_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT thread_owners_socket_generation_positive CHECK (socket_generation > 0)
);

CREATE INDEX idx_thread_owners_worker_lease
    ON thread_owners (worker_id, lease_until DESC);

CREATE TRIGGER trg_thread_owners_set_updated_at
BEFORE UPDATE ON thread_owners
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TABLE openai_socket_sessions (
    id text PRIMARY KEY,
    thread_id bigint NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
    root_thread_id bigint NOT NULL REFERENCES threads (id) ON DELETE CASCADE,
    parent_thread_id bigint REFERENCES threads (id) ON DELETE CASCADE,
    worker_id bigint NOT NULL REFERENCES workers (id),
    thread_socket_generation bigint NOT NULL,
    state text NOT NULL,
    connected_at timestamptz NOT NULL,
    last_read_at timestamptz,
    last_write_at timestamptz,
    last_heartbeat_at timestamptz NOT NULL,
    heartbeat_expires_at timestamptz,
    disconnected_at timestamptz,
    disconnect_reason text,
    expires_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT openai_socket_sessions_id_not_blank CHECK (btrim(id) <> ''),
    CONSTRAINT openai_socket_sessions_thread_socket_generation_positive CHECK (thread_socket_generation > 0),
    CONSTRAINT openai_socket_sessions_state_valid CHECK (
        state IN ('connected', 'disconnected')
    ),
    CONSTRAINT openai_socket_sessions_last_heartbeat_after_connect CHECK (
        last_heartbeat_at >= connected_at
    ),
    CONSTRAINT openai_socket_sessions_last_read_after_connect CHECK (
        last_read_at IS NULL OR last_read_at >= connected_at
    ),
    CONSTRAINT openai_socket_sessions_last_write_after_connect CHECK (
        last_write_at IS NULL OR last_write_at >= connected_at
    ),
    CONSTRAINT openai_socket_sessions_disconnected_after_connect CHECK (
        disconnected_at IS NULL OR disconnected_at >= connected_at
    ),
    CONSTRAINT openai_socket_sessions_connected_shape CHECK (
        (state = 'connected' AND disconnected_at IS NULL)
        OR (state = 'disconnected' AND disconnected_at IS NOT NULL)
    )
);

CREATE INDEX idx_openai_socket_sessions_thread
    ON openai_socket_sessions (thread_id, connected_at DESC);

CREATE INDEX idx_openai_socket_sessions_worker_state
    ON openai_socket_sessions (worker_id, state, connected_at DESC);

CREATE INDEX idx_openai_socket_sessions_connected_heartbeat
    ON openai_socket_sessions (heartbeat_expires_at ASC)
    WHERE state = 'connected';

CREATE INDEX idx_openai_socket_sessions_disconnected_expires
    ON openai_socket_sessions (expires_at ASC)
    WHERE state = 'disconnected';

CREATE TRIGGER trg_openai_socket_sessions_set_updated_at
BEFORE UPDATE ON openai_socket_sessions
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();
